Repository operate-first/community, pull requests merged in 2021-07, with the labels that each got.

#44 update the resource limit for the prowjobs
  .prow.yaml
Labels: approved, lgtm, size/XS

#43 Front page content draft
  new_front_page_mockup.md
Labels: approved, lgtm, size/M

#5 Created from existing messages for hacking-on
  core_project_message.md
Labels: approved, lgtm

#47 Updates to OWNERS file to add @margarethaley as a reviewer
  CONTRIBUTING.md
  OWNERS
  README.md
Labels: approved, lgtm, size/M

#48 Fixed bad manual merge, new content, is useful [squashed commits 3 in…
  CONTRIBUTING.md
  README.md
  contributing.md
Labels: approved, lgtm, size/M
