Repository operate-first/community, pull requests merged in 2022-04, with the labels that each got.

#167 [notes] First working session on docs gap analysis
  sig-community/wg-contrib_x-docs/meeting-notes/20220315-meeting-notes.md
  sig-community/wg-contrib_x-docs/meeting-notes/20220328-meeting-notes.md
Labels: size/M

#164 Creation of OPF personas as markdown files
  users/architect-it.md
  users/developer-qe.md
  users/generalpublic.md
  users/lineofbusiness.md
  users/sre-cloudoperator.md
  users/sysadmin.md
  users/undergrad-student.md
Labels: size/L, lgtm, approved

#171 open-source-services.md: Use word 'dependencies' for clarity
  open-source-services.md
Labels: lgtm, approved, needs-ok-to-test, size/XS

#176 SIG Community bi-weekly for 2022-04-07
  sig-community/meeting-notes/20220407-meeting-notes.md
Labels: lgtm, approved, size/M

#178 Minutes from not-a-meeting watercooler discussion
  sig-community/wg-contrib_x-docs/meeting-notes/20220411-meeting-notes.md
  sig-community/wg-website-updates/meeting-notes/20220412-meeting-notes.md
Labels: lgtm, approved, size/M

#162 Give more context on the reason for an all content open approach
  open-source-services.md
Labels: size/XS, ok-to-test

#179 Added links to Slack and Operate First community calendar
  README.md
  open-source-services.md
Labels: lgtm, approved, size/XS

#182 Fix typos and bad links
  sig-telemetry/README.md
Labels: lgtm, approved, size/XS
