Repository operate-first/community, pull requests merged in 2022-02, with the labels that each got.

#130 Add sig ops subprojects cluster-ops and ops-docs.
  generator/committee_readme.tmpl
  generator/header.tmpl
  generator/labels.md.tmpl
  generator/sig_readme.tmpl
  generator/ug_readme.tmpl
  generator/wg_readme.tmpl
  liaisons.md
  sig-list.md
  sig-operations/README.md
  sig-operations/subprojects/cluster-ops/OWNERS
  sig-operations/subprojects/ops-docs/OWNERS
  sigs.yaml
Labels: size/L, lgtm

#122 Minor corrections to README.md
  README.md
Labels: lgtm, approved, size/XS

#124 Strawpond charter for throwing pebbles at
  sig-community/charter.md
  sigs.yaml
Labels: approved, size/M

#135 Officially linking to new sig-community
  _toc.yml
  sigs.yaml
Labels: lgtm, approved, size/S

#133 Add Working Group Workload Overview
  OWNERS_ALIASES
  sig-list.md
  sigs.yaml
  wg-workload-overview/OWNERS
  wg-workload-overview/README.md
  wg-workload-overview/charter.md
Labels: lgtm, approved, size/M
