Repository operate-first/community, pull requests merged in 2022-03, with the labels that each got.

#143 Update sigops
  OWNERS_ALIASES
  sig-community/README.md
  sig-list.md
  sig-operations/README.md
  sigs.yaml
Labels: lgtm, approved, size/M

#145 add carlosgimeno to sig-operations/ops-docs subproject
  sig-operations/subprojects/ops-docs/OWNERS
Labels: lgtm, approved, size/XS

#144 Regenerate sigops files.
  sig-list.md
  sig-operations/README.md
  sigs.yaml
Labels: lgtm, size/XS

#146 Reflecting changes since forming SIG
  OWNERS
Labels: lgtm, approved, size/XS

#139 add Contrib_X Docs group
  sigs.yaml
Labels: lgtm, approved, size/S

#138 add Website Updates WG
  sigs.yaml
Labels: lgtm, approved, size/S

#152 updating pre-commit to use https instead of git urls
  .pre-commit-config.yaml
Labels: lgtm, approved, size/XS

#154 Clarify that requirement #1 applies to the Service itself
  open-source-services.md
Labels: lgtm, approved, size/XS, ok-to-test

#151 Add Meeting notes link to sig operations
  sig-operations/README.md
Labels: lgtm, approved, size/XS

#159 Directory structure for new working groups
  sig-community/wg-contrib_x-docs/meeting-notes/yyyymmdd-meeting-notes-template.md
  sig-community/wg-website-updates/meeting-notes/yyyymmdd-meeting-notes-template.md
Labels: size/M

#160 WG kickoff planning session, with actions
  sig-community/wg-contrib_x-docs/meeting-notes/20220315-meeting-ntoes.md
Labels: size/M

#161 First meeting minutes for new WG, more process needed
  sig-community/wg-website-updates/meeting-notes/20220322-meeting-notes.md
Labels: size/M

#163 Add definition of service to FAQ for open source service
  open-source-services.md
Labels: lgtm, approved, needs-ok-to-test, size/XS

#168 running generator
  OWNERS_ALIASES
  sig-list.md
  sig-operations/README.md
  sig-telemetry/README.md
  sigs.yaml
  wg-documentation/README.md
  wg-website/README.md
Labels: size/L, lgtm, approved
