Repository operate-first/community, pull requests merged in 2022-01, with the labels that each got.

#107 Governance 1.0 complete draft for discussion
  governance.md
Labels: size/L, lgtm, approved

#110 Updates from previous week
  program-management-tracker.md
Labels: approved, size/S

#113 Completion of draft stage, no longer WIP
  governance.md
Labels: lgtm, approved, size/XS

#114 Fixing forgotten content change of draft status
  governance.md
Labels: size/XS

#115 Add jupyterbook starter files and github action.
  _config.yml
  _toc.yml
  contributing.md
  img/favicon.png
  img/icon.png
  requirements.txt
Labels: lgtm, approved, size/M

#116 Add git action for jbook build.
  .github/workflows/book.yml
  yamllint-config.yaml
Labels: lgtm, approved, size/M

#117 Fix path to requirements file in gitaction.
  .github/workflows/book.yml
Labels: lgtm, approved, size/XS

#118 Fix path to pub dir in gitaction.
  .github/workflows/book.yml
Labels: size/XS

#120 Add operations sig charter and sig.yaml
  OWNERS_ALIASES
  _toc.yml
  generator/aliases.tmpl
  generator/committee_readme.tmpl
  generator/header.tmpl
  generator/labels.md.tmpl
  generator/liaisons.tmpl
  generator/list.tmpl
  generator/sig_readme.tmpl
  generator/ug_readme.tmpl
  generator/wg_readme.tmpl
  liaisons.md
  sig-list.md
  sig-operations/OWNERS
  sig-operations/README.md
  sig-operations/charter.md
  sigs.yaml
Labels: lgtm, approved, size/XL

#125 Update community metrics nb
  metrics/community_metrics.ipynb
Labels: size/L, lgtm, approved

#126 update metrics nb
  metrics/community_metrics.ipynb
Labels: approved, size/XL

#128 update nb with data fixes
  metrics/community_metrics.ipynb
Labels: size/L
